project_id = "hpyodaugrkctagkrfofj"

[functions.save-practice]
verify_jwt = true

[functions.mio-section-feedback]
verify_jwt = true

[functions.mio-chat]
verify_jwt = true

[functions.invalidate-cache]
verify_jwt = true

[functions.get-analytics]
verify_jwt = true

[functions.test-agents]
verify_jwt = true

[functions.populate-knowledge-base]
verify_jwt = false

[functions.migrate-nette-knowledge]
verify_jwt = false

[functions.send-user-invite]
verify_jwt = true

[functions.sync-analytics]
verify_jwt = true